name: flutter_food_delivery_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  syncfusion_flutter_charts:
  upgrader:
  captcha_solver:
  collection:
  flutter_timezone:
  flutter_local_notifications: ^13.0.0
  mobile_scanner:
  geocoding:
  qr_code_scanner:
  twilio_phone_verify:
  google_maps_flutter:
  esc_pos_utils:
  esc_pos_utils_plus:
  flutter_svg:
  flutter_foreground_service:
  equatable:
  provider:
  flutter_foreground_task:
  qr_flutter:
  flutter_rating_bar:
  geolocator:
  twilio_flutter:
  carousel_pro:
  esc_pos_printer:
  speech_to_text:
  open_file:
  syncfusion_flutter_pdf:
  path_provider:
  email_validator: ^1.0.6
  cupertino_icons:
  dio:
  flutter_slidable:
  flutter_tags:
  gallery_saver:
  screenshot:
  photo_view:
  flutter_stripe:
  chewie:
  video_player:
  money_converter:
  cnic_scanner:
  csc_picker:
  flutter_calendar_carousel:
  google_fonts:
  blinkid_flutter:
  file_picker:
  http:
  image:
  image_picker:
  intl:
  multi_image_picker:
  shared_preferences:
  url_launcher:
  dio_http:
  permission_handler:
  flutter_sms:
  google_mlkit_text_recognition:

dependency_overrides:
  stripe_android: "9.5.0+1"

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints:



flutter:
  generate: true
  uses-material-design: true
 # generate: true
#flutter_intl: enabled: true
